### ISSUE TITLE
Docker related stuff

### ISSUE THREAD

**Issue by redhog** [redhog/InfiniteGlass#21]
* Docker caching sometimes screws things up - maybe mount python code from outside?

**Comment by BackOrder** [comment]
Default directory when opening a shell is /InfiniteGlass instead of /home/glass.

**Comment by redhog** [comment]
Hm, yeah... that's an effect of running using "make run" instead of as a full desktop started by Gdm/Xdm, which is what run-in-docker does... Not sure I can even fix that, sorry :(

**Comment by BackOrder** [comment]
Something seems wrong here. [20200212-1727.log](https://github.com/redhog/InfiniteGlass/files/4195330/20200212-1727.log)

![image](https://user-images.githubusercontent.com/8844578/74383133-a4a9c000-4dbc-11ea-9324-6c4a19e4efb6.png)

> Default directory when opening a shell is /InfiniteGlass instead of /home/glass.

Perhaps using WORKDIR in the Dockerfile would work?

**Comment by redhog** [comment]
Oh no, not that bug again :( There is a bug in the SMlib parser code in pysmlib, where it either chops of the last character of RestartCommand for some apps, or leaves an extra NULL byte for other apps. I seriously don't know how that code *should* work... But I do know an ugly workaround...

**Comment by BackOrder** [comment]
The docker performances are drastically better when increasing the container memory size. Allocating 2 GB memory seems to be good. `-m 2gb` in `scripts/run-in-docker.sh`. Probably still slower than Xephyr but the improvement is noticeable.

**Comment by redhog** [comment]
I've implemented the memory thing, and I'll close this ticket. You can make a new one if you find more Docker related stuff :)
