### ISSUE TITLE
Usability problems

### ISSUE THREAD

**Issue by redhog** [redhog/InfiniteGlass#23]

**Comment by BackOrder** [comment]
Double click is a little slow in drun. There are not much apps into the container to thoroughly test. Double click works fine in the help window.

**Comment by redhog** [comment]
What is double click supposed to do? Start apps? I always just start with ENTER so I didn't know... I'll test.

As for apps, maybe there's a ubuntu image that contains more apps by default? A full set of normal ubuntu-desktop apps would be useful for sure. Esp to test the session/ghost support, as quite a few apps have none/very crappy state saving abilities.

So far I've tested and gotten Pluma (gedit?), Chromium (with hack) and Emacs (with config) to work. However, emacs is still a bit buggy... This will definitely be quite some work to get fully useful, and there will always be apps with bad support :(

**Comment by redhog** [comment]
On that note, I'd love it if were to test / configure / hack around limitations of session saving support for apps you're interested in!

**Comment by BackOrder** [comment]
> On that note, I'd love it if were to test / configure / hack around limitations of session saving support for apps you're interested in!

I'm concerned with overwhelming you with requests without properly contributing to your project. Likewise, don't be shy if you want me to test things out that can be done during my spare time.

I could however install some apps in the container using apt-get and report on my experience.

Enter works as expected in drun. That's the snappy response I would expect from a double click. Different user, different usage!

**Comment by redhog** [comment]
Well, testing is a good type of contribution right now! Not that I'd say no if you started hacking / configuring stuff either :p 

Right. Hm, so something to do with mouse interaction then...

**Comment by BackOrder** [comment]
Atom is working on your WM! What's the password of root on the docker image?

```bash
docker exec -it glass bash
wget -qO - https://packagecloud.io/AtomEditor/atom/gpgkey | apt-key add -
sh -c 'echo "deb [arch=amd64] https://packagecloud.io/AtomEditor/atom/any/ any main" > /etc/apt/sources.list.d/atom.list'
apt-get update
apt-get install atom
```
![image](https://user-images.githubusercontent.com/8844578/74293052-99e12380-4d07-11ea-9371-a1ad9e66b7f5.png)

**Comment by redhog** [comment]
Cool!

Don't think there is a root password, but also there's no sudo installed or anything. It's the barebone ubuntu docker image. But I guess we could set a default password if that's useful, hm...

**Comment by BackOrder** [comment]
Yes, we need to be able to access root. I'd like to do everything within the WM. That's the best test for usability. :D

What kind of restrictions your WM has? It seems that most applications I installed run just fine.

Windows decorations would be nice. Minimize, maximize and close. Perhaps having a key modifier to display them if you prefer. Seems like you do everything with the keyboard. :)))

**Comment by redhog** [comment]
Well, yeah, but there are quite some mouse bindings too, but no decorations. A mouse with a wheel is a +, as the wheel can be used to zoom (instead of pgup/down, with the same modifiers)....

**Comment by redhog** [comment]
Btw, just realized, you can do

    cd ~

in ~/.config/glass/session.sh to fix the workdir problem...

**Comment by redhog** [comment]
Re. root, check out latest master. The change is this:https://github.com/redhog/InfiniteGlass/commit/c22349ae7cf3b9c13cb20b7f3bafee5b4c3a86ef

**Comment by BackOrder** [comment]
The workdir solution works but not root (both su and sudo) even after `docker rmi -f redhogorg/glass:0.0.2` to rebuild the image.

There are few shortcuts that I am not yet familiar in `~/.config/glass/input.json`. Do you have a README or something? How to use the resize shortcut? Also, if numlock is on before launching the WM, numlock doesn't work anymore and it's always on.

How to make a window on top when two windows are overlapping? How do you move from one window to another with a keyboard?

WINDOWSKEY+Arrows is a little too fast for me. It would be nice to have the scroll click be equivalent to WINDOWSKEY+Right click.

**Comment by redhog** [comment]
Hm, sudo worked for me. Can you check the content of your Dockerfile for mentions of sudo?

Unfortunately I haven't had time to document all the actions available to input.json. Which ones are you wondering about? Maybe I have just given them crappy names?

So WINDOWS+CONTROL+ALT and click on a window and move the mouse will resize it, and also change its resolution correspondingly, keeping the same ratio of screen-pixels to window-pixels.

These two issues haven't been addressed yet. I'll try to fix them soon.

Hm, I think this is the point where we might need videos and / or a skype call to figure out what you'd like to work how... I'm not 100% sure I understand what you mean properly...

**Comment by BackOrder** [comment]
> Hm, sudo worked for me. Can you check the content of your Dockerfile for mentions of sudo?

The following is working. Please, confirm it's working for you as well.

```Dockerfile
 RUN useradd glass && echo "glass:glass" | chpasswd && adduser glass sudo
 RUN mkdir -p /home/glass
 RUN chown glass:glass /home/glass
 RUN chmod -R ugo+rw /InfiniteGlass
 
 USER glass
```

> These two issues haven't been addressed yet. I'll try to fix them soon.

No worries.

> Hm, I think this is the point where we might need videos and / or a skype call to figure out what you'd like to work how... I'm not 100% sure I understand what you mean properly...

This is a good idea. I will check when I have free time and get back to you on this one.

**Comment by BackOrder** [comment]
Sudo still has a problem: it asks for a password, even with your sed command.

**Comment by redhog** [comment]
I'm pretty sure your sudo problem is a docker caching problem, namely that even if you delete the image tag, the container is still there, hanging off of a now utagged image... Can you try git pull and then

    make clean

followed by

    make run-in-docker

? Make clean now deletes the docker image and the named docker container. If this doesn't work I'll change to your code above...

**Comment by BackOrder** [comment]
Ewh, it did some damages. [notes-20200214.txt](https://github.com/redhog/InfiniteGlass/files/4207436/notes-20200214.txt)

**Comment by redhog** [comment]
Ah yeah, sorry, that's a small breaking change I did some commits ago (renamed the table ghosts from shadows). If you delete your ~/.config/glass/ghosts.sqlite3 you should be good!

**Comment by redhog** [comment]
I did a pretty big naming cleanup, among other things making sure to not use ghosts and shadows randomly to refer to the same thing... It was pretty ugly and mostly a historical screwup...

**Comment by BackOrder** [comment]
It's running again after removing the file and yet another make clean. There is another problem you can see in the log file. However, now xterm shows up when the WM is running. Even got the nice animation for WINDOWS-ESC dock.

[notes-20200214-1952.txt](https://github.com/redhog/InfiniteGlass/files/4207526/notes-20200214-1952.txt)

On a side note, as far as usability goes, copy-paste doesn't work from my desktop to your WM. Select text and scroll-click within the WM does work though.

**Comment by redhog** [comment]
Hm, might have to rm ~/.config/glass/ghosts.json too... I seem to have steamed ahead quite a few versions from what you have been running for a while inside your docker now :P Oupsi...

**Comment by BackOrder** [comment]
> Hm, might have to rm ~/.config/glass/ghosts.json too... I seem to have steamed ahead quite a few versions from what you have been running for a while inside your docker now :P Oupsi...

No worries, really. Having a new user is definitively a good test for your WM. Perhaps I should `git pull` more often though. ;)

**Comment by redhog** [comment]
Yeah, I mean, that would subject you to more breakage, but also more fun new stuff, and fixed bugs...
And yes, having a user that isn't me definitely helps with self-discipline of code organization and documentation....

**Comment by BackOrder** [comment]
Take your time. I'm enjoying your WM and don't mind things breaking.

**Comment by redhog** [comment]
Btw, re git pull: do a pull now and tell me what you think about the new WINDOWS+ARROWKEY and WINDOWS+PGDOWN/PGUP behaviours.... They're a bit "smarter" now...

**Comment by BackOrder** [comment]
The arrow keys are smooth and nice. This is definitely an improvement. Moving outward the windows is somehow strange. And zooming might still need a little work because it doesn't feel as much natural as arrow keys are now.

**Comment by redhog** [comment]
Hm, so what would you like to happen when you change focus to a window outside the current view? Or is it the right thing, just the animation not being the way you'd like it?

**Comment by BackOrder** [comment]
> Hm, so what would you like to happen when you change focus to a window outside the current view? Or is it the right thing, just the animation not being the way you'd like it?

This is a very good question. Moving from a window to another is super smooth. Moving outward is a bit like getting lost somewhere. Perhaps I just need to get used to it? In a way, the point is to have an infinite workspace... A mini map might help (that can be toggled on/off, WINDOWS-M or such) or something to help us to know where our windows are. What do you think?

**Comment by redhog** [comment]
A mini map has been a plan for a long time... it just requires a bit of work to figure out exactly how to implement it.. So let's talk about what we can do without that first? Are there any hints (animation, borders, colors) I could give to help you feel less lost?

**Comment by BackOrder** [comment]
> Are there any hints (animation, borders, colors) I could give to help you feel less lost?

Yes, hints would be fine for now. Hints could be displayed on any borders where there are windows (from the center of the screen towards the window) while moving around. Whatever you have in mind could be fine. You can have a dot or something.

**Comment by redhog** [comment]
Check out this change here: https://github.com/redhog/InfiniteGlass/commit/46ca50d06b05b5ff2b8dedba7b3f39967147228e it adds edge-hinting... It was actually surprisingly easy to implement :) Let's see how you like that...

**Comment by BackOrder** [comment]
It turns out great! The user experience feels much better. You did a fantastic job. :)

**Comment by redhog** [comment]
:) Cool! Sometimes the simple solutions are the best...

**Comment by BackOrder** [comment]
Moving around sometimes mess with the aspect ratio of the windows:

![image](https://user-images.githubusercontent.com/8844578/74856580-55114a00-5310-11ea-8f6d-3259920ee9cc.png)

Normal:

![image](https://user-images.githubusercontent.com/8844578/74856630-68bcb080-5310-11ea-9a10-ea638bcf7b6d.png)

**Comment by redhog** [comment]
That is indeed a funny bug... Did you zoom in and out far, or what did you do to trigger this?
It is a bit of an issue that sizes are stored as width,height, not with,aspectratio, so they are subject to rounding errors, and compound rounding errors... Not sure this is the case here though...

**Comment by BackOrder** [comment]
Yes, I did zoom in and out. I did test with only moving around after you mentioned it and it eventually comes up again. The test is simple: open Audacity, move around, open xterm, move around, open another xterm, move around, etc. until it breaks the aspect ratio.

![image](https://user-images.githubusercontent.com/8844578/74867314-724f1400-5322-11ea-91b0-3d60df117021.png)

**Comment by redhog** [comment]
Hm... so maybe it's a race condition then? Hm... I'll see if I can debug this...

**Comment by BackOrder** [comment]
Another thing that would be nice: WIN-ESC menu would appear when the mouse is nearby. Not a super fan of WIN-ESC since it requires one hand to leave the main row.

**Comment by BackOrder** [comment]
The mouse cursor is the old X Window cross that is usually used to kill windows or when a zone is unclickable. Couldn't we have one of your fancy SVG? :)

I'd like to suggest a dot surrounded by a circle. It would fit with the spirit of your WM. Perhaps the outer circle could shrink when we click. Also, on Gnome I use CTRL to find the mouse cursor..  so you could have an animation of your choice there.

**Comment by redhog** [comment]
I've split the remaining issues into separate tickets, and I'm closing this one - it's getting to big. Let's try having more and smaller tickets :)
