### ISSUE TITLE
Docker wget issue?

### ISSUE THREAD

**Issue by redhog** [redhog/InfiniteGlass#25]
The file /InfiniteGlass/glass-widgets/glass_widgets/fontawesome-free-5.9.0-desktop/svgs/solid/search-plus.svg is missing, see [20200208-1255.log](https://github.com/redhog/InfiniteGlass/files/4174875/20200208-1255.log)

@BackOrder, could you possibly do a docker exec into the container, go to /InfiniteGlass/glass-widgets/ and run "python setup.py install" and check for any error messages? This should try to download the Font Awesome, which is what I use for the icons in the sidebar...

**Comment by BackOrder** [comment]
Well, isn't the world go round?

```
docker start glass              1 ↵
glass
docker exec -it glass bash
root@eba320067d85:/# cd /InfiniteGlass/glass-widgets/
root@eba320067d85:/InfiniteGlass/glass-widgets# ls
MANIFEST.in  glass_widgets  glass_widgets.egg-info  setup.py
root@eba320067d85:/InfiniteGlass/glass-widgets# python setup.py install
Traceback (most recent call last):
  File "setup.py", line 3, in <module>
    import setuptools
ImportError: No module named setuptools

```

**Comment by redhog** [comment]
Sorry, try python3 instead...

**Comment by BackOrder** [comment]
Yes, wget and unzip are missing. [20200208-1401.log](https://github.com/redhog/InfiniteGlass/files/4174980/20200208-1401.log)

**Comment by redhog** [comment]
Fixed, check https://github.com/redhog/InfiniteGlass/commit/f2c6ad2fbdd45afa83641809ace144981bce3fc1

So if you do a git pull and remove your docker image it should be fixed :)

**Comment by BackOrder** [comment]
It's working but `scripts/run-in-docker.sh` did not update the container after I ran `docker rm <container id>`. Had to run `docker build -t redhogorg/glass:0.0.2 .` manually. All errors except Xlib.xauth errors are gone.

**Comment by redhog** [comment]
You need to do "docker rmi redhogorg/glass:0.0.2" for run-in-docker to rebuild the image...

Not sure how to fix the Xauth errors, but if you can see anything at all, they're not really relevant, so I'd say for now just ignore them :)
