### ISSUE TITLE
Theme support

### ISSUE THREAD

**Issue by BackOrder** [redhog/InfiniteGlass#31]
Theme related topics. Window decoration, colour scheme, wallpaper, etc.

**Comment by redhog** [comment]
glass-theme is not really currently configurable. However, all it sets up is delivered to other components over properties, and it has extensive control over the display of windows, background, init splash animation etc... This should maybe be documented better?

As for window decorations, the IG_SVG datatype needs a way to specify a coordinate offset and size (if we are to use svg buttons, but I think that's the right thing to do :).

**Comment by BackOrder** [comment]
> RE: glass-theme, documentation

More documentation would certainly help. Though everything you do is well organized. :)

> As for window decorations, the IG_SVG datatype needs a way to specify a coordinate offset and size (if we are to use svg buttons, but I think that's the right thing to do :).

Most WMs have to provide images of various sizes to satisfy the diversity of screen resolutions. Using SVG throughout makes a lot of sense.

Glass-theme could perhaps be configurable via json or css, if that's not already the case. The idea is to keep things simple. Gnome, for example, is difficult to customize and most themes beside Adwaita have issues.

**Comment by redhog** [comment]
Just tell me which of the action names in input.json you don't know what they do and I'll try to document or rename them so that they make sense...

So... glass-theme right now is just a very short python, plus OpenGL shader code program and not at all configurable. Actually, maybe you should have a look at that code and see if you could do something fun with it? I'll think about ways to make it generic and configurable in a bit - I need to fix some performance problems with rendering right now :(

**Comment by BackOrder** [comment]
> RE: input.json

Alright, I will do this!

> RE: glass-theme

I am a bit limited in time lately and my plan was to build a newer version of Xorg with Xephyr. However, the gain in performance on docker when memory is increased (see [comment](https://github.com/redhog/InfiniteGlass/issues/21#issuecomment-585990649)) might be enough to focus on the WM instead.

> RE: OpenGL

How difficult would it be to implement using Vulkan API? :p

**Comment by redhog** [comment]
Re Vulcan: No idea, I haven't programmed Vulcan ever. However, I do a lot of stuff in the shader code, so depends on how different the shader language is I guess?

**Comment by redhog** [comment]
Re. input.json: I've made a tool to pretty-print your current keybindings in a simplified format. It will possibly exclude some more complicated combinations, but should give you a good overview over most stuff:

    glass-action keybindings

**Comment by redhog** [comment]
Just implemented a subclassable theme system. Themes are mostly defined in terms of shaders. See https://github.com/redhog/InfiniteGlass/blob/master/docs/THEMES.md

**Comment by BackOrder** [comment]
This is an excellent news!
