### ISSUE TITLE
Aspect ratio sometimes gets hosed after moving around

### ISSUE THREAD

**Issue by redhog** [redhog/InfiniteGlass#34]
Split out from https://github.com/redhog/InfiniteGlass/issues/23

Moving around sometimes mess with the aspect ratio of the windows:

![image](https://user-images.githubusercontent.com/8844578/74856580-55114a00-5310-11ea-8f6d-3259920ee9cc.png)

Normal:

![image](https://user-images.githubusercontent.com/8844578/74856630-68bcb080-5310-11ea-9a10-ea638bcf7b6d.png)

**Comment by redhog** [comment]
That is indeed a funny bug... Did you zoom in and out far, or what did you do to trigger this?
It is a bit of an issue that sizes are stored as width,height, not with,aspectratio, so they are subject to rounding errors, and compound rounding errors... Not sure this is the case here though...

**Comment by redhog** [comment]
Yes, I did zoom in and out. I did a test with only moving around after you mentioned it and it eventually comes up again. The test is simple: open Audacity, move around, open xterm, move around, open another xterm, move around, etc. until it breaks the aspect ratio.

![image](https://user-images.githubusercontent.com/8844578/74867314-724f1400-5322-11ea-91b0-3d60df117021.png)

**Comment by redhog** [comment]
Fixed here: https://github.com/redhog/InfiniteGlass/commit/cc570ae05b42b0c00a182ab29c618b76edddb602

**Comment by BackOrder** [comment]
Seems to be fixed. One thing that is annoying when I use the WINKEY is that changing focus on xterm grab the input and subsequent WIN+ARROWS are swallowed by the xterm. Nothing should be able to grab the input while using WINKEY. And, I'm still enjoying the edge highlight very much. :D

**Comment by redhog** [comment]
Yeah, I've seen the WINKEY swallowing by other apps too, esp Chrome. I really have no idea how those apps can override a XGrabKey on the root window. There are still parts of the X protocol that I'm a bit unsure of - and this stuff isn't that well documented :(

**Comment by BackOrder** [comment]
https://bugs.freedesktop.org/show_bug.cgi?id=39545

Seems like a bug but the question is... How other WMs do it?

**Comment by redhog** [comment]
Oh... maybe thats's it? If so, there is very little I could do I think? But not sure this is actually it... What I do is:

XGrabKey(WINDOWS)
User presses WINDOWS.
XGrabKeyboard()
User presses and releases a bunch of stuff, I use it all
User releases WINDOWS
XUngrabKeyboard()

**Comment by BackOrder** [comment]
Would it be possible to somehow disable all windows (or just their input) when WINKEY is pressed? Then you go through the list again to reenable when the key is released.

**Comment by redhog** [comment]
Hm, isn't that what XGrabKeyboard is supposed to do?!

**Comment by BackOrder** [comment]
> Hm, isn't that what XGrabKeyboard is supposed to do?!

Yes. o_O

Or, could you check if WINKEY is already press when another window grab the input? If it's press, have it skip the grab, otherwise grab it as usual.
