### ISSUE TITLE
Background colour (or image)

### ISSUE THREAD

**Issue by BackOrder** [redhog/InfiniteGlass#38]
How to change the background colour? Is it possible to set an image?

A colour is fine for me though. It's all too hospital feeling right now. So white.

**Comment by redhog** [comment]
You can easily change the background color, or make a pattern, in

    glass-theme/glass_theme/shaders/root/fragment.glsl

- or override this file in your own theme subclass. You probably want to change

    glass-theme/glass_theme/shaders/splash_background/fragment.glsl

too or you'll have a bit of a funny entry animation (it'll just fade over to the desktop color from the globe color, but that's a bit funny, isn't it)...

Maybe this should not be hardcoded in the shader though...

Picture is harder but far from impossible. But: If you want it to move when the desktop moves, you need some more magic, and making it look good is gonna be hard. My long-term goal is a fractal...

**Comment by BackOrder** [comment]
Fractals are a very good idea. I will try changing the colour in the meantime and see how it goes.

**Comment by redhog** [comment]
Cool! You should try making a theme that does it, that would be a very good test-case for the theming engine, and for my documentation on that...

**Comment by BackOrder** [comment]
Changing both glsl didn't do anything until `make clean` and build all over again. Any quicker way?

Also, what is the format for the colours? I assumed it was rgba but didn't turned out too well. :D

> Cool! You should try making a theme that does it, that would be a very good test-case for the theming engine, and for my documentation on that...

That could be something interesting. I was looking for something to start with.

**Comment by redhog** [comment]
It should be rgba, in the range 0..1.
Hm, that's just because you're inside a docker :( You have a copy of everything in there, and it's only copied in again when you rebuild the image. But you could edit the file inside the container if you exec in. All the files are under /InfiniteGlass....

**Comment by BackOrder** [comment]
![image](https://user-images.githubusercontent.com/8844578/75078747-83d81d80-54d4-11ea-8a3a-3af57ce9b54a.png)

It's working inside the container. And the 70s are back.

**Comment by redhog** [comment]
Haha, fantastic :P Not sure I think it's that much more aesthetic, but sure, to each his own :P The double borders do look nice this way though....

**Comment by BackOrder** [comment]
> Haha, fantastic :P Not sure I think it's that much more aesthetic, but sure, to each his own :P The double borders do look nice this way though....

Haha, I wanted something to contrast with the colour of my desktop (a comforting green). Agreed on the double borders. They look nice. By the way, would it be possible to change the colour and reapply while using the WM?

**Comment by redhog** [comment]
Yep, but it's a tiny bit tricky. Check out

    glass-action component list

and

    glass-action component restart NAME

But restarting glass-theme would rerun the intro animation... and avoiding that is the tricky part...

**Comment by redhog** [comment]
Very untested btw.... only component I restart often is glass-input...

**Comment by BackOrder** [comment]
> Very untested btw.... only component I restart often is glass-input...

I'm your dedicated crash test dummy. ;)

**Comment by redhog** [comment]
hehe, yep. and that's fantastic!

**Comment by BackOrder** [comment]
The result from `glass-action component restart glass-theme` is in... rolling drums...

```
59
Traceback (most recent call last):
  File "/InfiniteGlass/glass-lib/InfiniteGlass/display.py", line 30, in handle_x_event
    if handler(event):
  File "/InfiniteGlass/glass-lib/InfiniteGlass/display.py", line 101, in handler
    return fn(self, event)
  File "/InfiniteGlass/glass-lib/InfiniteGlass/window.py", line 72, in handler
    return fn(self, event)
  File "/InfiniteGlass/glass-ghosts/glass_ghosts/components.py", line 24, in PropertyNotify
    self.start_component(spec)
  File "/InfiniteGlass/glass-ghosts/glass_ghosts/components.py", line 63, in start_component
    del self.components_by_pid[pid]
KeyError: 59
```

**Comment by BackOrder** [comment]
https://github.com/danilobellini/fractal

**Comment by redhog** [comment]
Ah right... because glass-theme exits immediately after the initial zoom, and is never restarted.... But, an explicit restart _should_ start it even if it isn't running. That's a bug I guess...

**Comment by redhog** [comment]
Moved the restart stuff to https://github.com/redhog/InfiniteGlass/issues/43
