### ISSUE TITLE
Gnome-terminal doesn't work

### ISSUE THREAD

**Issue by BackOrder** [redhog/InfiniteGlass#40]
Running Gnome-terminal (and vim) causes the following error:

```
# Error constructing proxy for org.gnome.Terminal:/org/gnome/Terminal/Factory0: 
  Error calling StartServiceByName for org.gnome.Terminal:
    GDBus.Error:org.freedesktop.DBus.Error.Spawn.ChildExited: 
      Process org.gnome.Terminal exited with status 8
´´´

**Comment by redhog** [comment]
Another dbus problem :(

**Comment by BackOrder** [comment]
https://askubuntu.com/questions/608330/problem-with-gnome-terminal-on-gnome-3-12-2

Here they say locale is a problem. I'm usually using **fr_CA.UTF8** and it causes all sort of problems including when using `glass-action`.

The following didn't fix gnome-terminal for me but selecting en_US.UTF-8 and restarting the WM did fix `glass-action`.
```
sudo apt install dconf-cli
dconf reset -f /org/gnome/terminal
sudo apt-get remove gnome-terminal
sudo apt-get install gnome-terminal
sudo apt-get install -y locales
sudo locale-gen --purge
sudo dpkg-reconfigure locales
reboot
```

**Comment by redhog** [comment]
That seems so buggy! It doesn't work with any UTF8 locale, just en_US?!

I mean, fair enough if it didn't like non-utf locales, but that's not the problem here?!

**Comment by BackOrder** [comment]
So far it hasn't been working properly but I had updated my system's glibc to the latest version (uses UTF8 instead of UTF-8). I will try again with my locale but UTF-8 instead.

Not sure what the problem is for gnome-terminal but some apps (such as glass-action) didn't work otherwise. So clearly there are a few things to fix here.

**Comment by redhog** [comment]
All my python code is python 3, so it should theoretically be all unicode. Not that I have tested it much apart from window titles...

**Comment by redhog** [comment]
Btw, you're a good test user - you trigger all the bugs :P

Also on a totally different note: I've changed the tiling algorithm (WINDOWS+T). It's better, but not perfect yet,..

**Comment by BackOrder** [comment]
> All my python code is python 3, so it should theoretically be all unicode. Not that I have tested it much apart from window titles...

The bug is not in your python code.

> Btw, you're a good test user - you trigger all the bugs :P

It's been a natural talent that got me into more troubles than I can count. :D

> Also on a totally different note: I've changed the tiling algorithm (WINDOWS+T). It's better, but not perfect yet,..

Noticed already. Sometimes it does really well, some other times it puts everything on one side.


> RE: gnome-terminal

https://wiki.gnome.org/Apps/Terminal/FAQ#Exit_status_8

> RE: glass-action

So, I ran `sudo dpkg-reconfigure locales`, selected my locale, rebuilt the locales and restarted the WM. Glass-action now works without warning. It might be because I'm running a newer glibc where they decided to change UTF-8 into UTF8. Perhaps you could try with a Swedish or Norwegian locale and see if it needs to be fixed or not.

**Comment by BackOrder** [comment]
Speaking of tiling...

![image](https://user-images.githubusercontent.com/8844578/75082033-b3405780-54df-11ea-88a7-abfb3217b747.png)

**Comment by redhog** [comment]
That's the old tiling algorithm I think. The new one has a tendency to do a similar thing, but along the bottom edge... This is a hard problem (NP-complete), and getting a good heuristic for most cases is still hard...

**Comment by BackOrder** [comment]
> RE: Glass-action

Dockerfile needs the following:

```
RUN apt install -y locales
RUN apt install -y locales-all
RUN locale-gen en_US.UTF-8
```

**Comment by BackOrder** [comment]
> That's the old tiling algorithm I think. The new one has a tendency to do a similar thing, but along the bottom edge... This is a hard problem (NP-complete), and getting a good heuristic for most cases is still hard...

Window placement is somewhat a problem in InfiniteGlass. The terminal on startup is in the left corner but would be best a little more towards the center. Also, I have no idea how to bring to front a window and often an xterm is stuck at the back and I must move it to use it.

**Comment by redhog** [comment]
Initial window placement has its own ticket: https://github.com/redhog/InfiniteGlass/issues/11
You should be able to switch focus to the new window using CTRL+WIN+ALT+ARROWKEY, but I guess that's a bit clumsy. New windows should perheaps steal focus?

**Comment by redhog** [comment]
Added your locale lines to Dockerfile

**Comment by BackOrder** [comment]
Hmmm. It doesn't fix the gnome-terminal problem though. :)

We might perhaps need more gnome dependencies?

**Comment by redhog** [comment]
Feel free to experiment with what's needed inside the container and I'll add it to the dependency list.
Alternatively, try use mate-terminal? Might need the same though...

Maybe we should just do "apt install ubuntu-desktop"? It just means build is gonna be sloooow...

**Comment by BackOrder** [comment]
> Maybe we should just do "apt install ubuntu-desktop"? It just means build is gonna be sloooow...

This is exactly what I am doing right now. At least to know it can work in your WM. We can sift through packages needed later on.

**Comment by BackOrder** [comment]
Well, it didn't help a bit. 1.3GB of dead weight. :)

**Comment by redhog** [comment]
:(

**Comment by redhog** [comment]
Can you run gnome-terminal outside the docker container? If so, you could forward the x socket out from the container... it's :100....

**Comment by BackOrder** [comment]
I'm using gnome-terminal on my desktop. However, there are nice alternatives out there. I tried Terminology and it is absolutely great but it has a lot of dependencies. Sakura seems to be light and would certainly do. Have a try and pick one for docker. :D

**Comment by BackOrder** [comment]
Interestingly, it seems that your WM does not support transparency. I usually set my terminal with some light transparency.

Sakura:
![image](https://user-images.githubusercontent.com/8844578/75098259-fd7a1500-5581-11ea-86a3-2dc52eecf052.png)

Terminology:
![image](https://user-images.githubusercontent.com/8844578/75098280-2a2e2c80-5582-11ea-8760-48b2bb8d5d34.png)

**Comment by BackOrder** [comment]
Sakura should be the one we include in docker because Terminology has some issues in the menu and options. Little dependencies, good features and last release is 2019-08-12.

**Comment by redhog** [comment]
Hm... Transparency shouldn't be too hard to implement I think. I just don't know where the alpha channel comes from when you do CompositeRedirect... as in, I don't know how to read it out from the window... probably super easy, I just never checked.

**Comment by redhog** [comment]
Moved to here: https://github.com/redhog/InfiniteGlass/issues/45
