### ISSUE TITLE
Special Request (Shell)

### ISSUE THREAD

**Issue by BackOrder** [redhog/InfiniteGlass#42]
The bourne shell... is a tad outdated. How about we use zsh instead? Zsh with Oh-My-Zsh would up the cool factor for sure.

https://github.com/ohmyzsh/ohmyzsh
https://github.com/powerline/fonts (most themes require Powerline fonts)

You can even choose a theme that would go well with InfiniteGlass. Though most themes are on black window. Not sure the default terminal can be black. Gnome-terminal supports background colour and transparency but, alas, #40 .

```
RUN apt install -y git
RUN apt install -y curl
RUN apt install -y zsh
```

**Comment by BackOrder** [comment]
Interestingly, your demo on Reddit shows zsh in action. :)

**Comment by redhog** [comment]
Also, terminal:

Sakura should be the one we include in docker because Terminology has some issues in the menu and options. Little dependencies, good features and last release is 2019-08-12.

**Comment by redhog** [comment]
Nah, the reddit video is with bash, and a bit of a hacked up powerline...

**Comment by BackOrder** [comment]
> Nah, the reddit video is with bash, and a bit of a hacked up powerline...

bash and me, we ain't no friend. :(

**Comment by BackOrder** [comment]
`glass-action component restart glass-theme` works now but it still need to define `export LANG=en_US.UTF-8`. This should be added in the resource file (sh, bash, zsh).

![image](https://user-images.githubusercontent.com/8844578/75118289-dfc2b380-5646-11ea-9f5e-5405a70b69c7.png)

**Comment by BackOrder** [comment]
Ultimately, the code should support other locales. 

Well... it's fun to change the background. The more InfiniteGlass becomes usable, the more I'm enjoying it! It feels natural to use compared to Windows imitations like Gnome/KDE.

**Comment by redhog** [comment]
Awesome! That really is my goal - to not imitate anything, but rather just try to make something that makes sense in and of itself...

Hm, couldn't we set that env variable in the Dockerfile using ENV? All locales should work, but: There is only so much time I want to spend on issues that only exist inside docker...

**Comment by BackOrder** [comment]
> Awesome! That really is my goal - to not imitate anything, but rather just try to make something that makes sense in and of itself...

I'm your biggest fan, really! :)

> Hm, couldn't we set that env variable in the Dockerfile using ENV? All locales should work, but: There is only so much time I want to spend on issues that only exist inside docker...

So sorry about that. I haven't had time to figure out how to build the newest version of XOrg. It's on my task list though. Xephyr performances will be better outside Docker, one could suppose.

You are correct, the following is working in Dockerfile: `ENV LANG en_US.UTF-8`

**Comment by redhog** [comment]
I'm updating the docker file with the env variables as well as your apt installs above. You'll have it pushed as soon as docker has built the image so I know it works :)

**Comment by BackOrder** [comment]
> I'm updating the docker file with the env variables as well as your apt installs above. You'll have it pushed as soon as docker has built the image so I know it works :)

By the way, I can occasionally do it on my own if you add me to your project on Github. That would save you at least from that kind of little things.

**Comment by redhog** [comment]
https://github.com/redhog/InfiniteGlass/invitations

**Comment by redhog** [comment]
Please make changes on new branches (one per feature) and make pull requests. If they're trivial, you can just merge them yourself, otherwise I'll have a look and merge...

**Comment by redhog** [comment]
Pushed the changes

**Comment by BackOrder** [comment]
Take a look at my first commit. :)

**Comment by BackOrder** [comment]
> lease make changes on new branches (one per feature) and make pull requests. If they're trivial, you can just merge them yourself, otherwise I'll have a look and merge...

Oh, okay!

**Comment by redhog** [comment]
I like PR:s, they make it tidy and easy to follow why stuff got committed...
