### ISSUE TITLE
Window Decorations

### ISSUE THREAD

**Issue by BackOrder** [redhog/InfiniteGlass#44]
Implementation tasks:

* [X] Windows referenced as properties
  * [X] Relatively positioned windows
* [x] Click handling on relatively positioned windows
* [x] Bugfix picking with referenced windows
* [x] Bugfix active window with referenced windows

![image](https://user-images.githubusercontent.com/8844578/75095521-846bc500-5563-11ea-9b6f-93b243e968d3.png)

I suggest the window decorations appear on the side of the window closest to the mouse cursor, as a practical matter.

**Comment by BackOrder** [comment]
They should remain hidden until the mouse is nearby. :)

**Comment by redhog** [comment]
That looks really stylish!

**Comment by BackOrder** [comment]
Glad you like it! I've used the following Icon Packs, both available with a CC license and SVG. Be aware that some icons seem not to be downloaded in the archive, you might have to download individually.

https://www.flaticon.com/packs/the-essentials-3
https://www.flaticon.com/packs/essentials-13

**Comment by BackOrder** [comment]
Further details on the usability:

- Window decorations appear only when the mouse is nearby and the focus is on the given window
- Window decorations will populate one of the corner/side the closest to the mouse cursor
- The close button should always be outward the center of the window
- Some animation would be nice, e.g. ease in/out or fade in/out

**Comment by BackOrder** [comment]
We could also perhaps consider adding an icon to move the window. Some keyboard shortcuts combined with the mouse isn't particularly easy but we can help things out with some shorthand.

**Comment by BackOrder** [comment]
Most WM will have a background on various GUI components to avoid the problem in the screenshot. However, I would like to suggest that windows underneath WIN-ESC menu or Windows decorations should become transparent. Not completely but enough to see icons properly.

![image](https://user-images.githubusercontent.com/8844578/75114628-a9c10780-5625-11ea-8ab3-dc6e92cffa36.png)

**Comment by redhog** [comment]
Oh, that might be a bit hard to implement (the transparency)...
So, the way things are drawn is bottom to top, one window at a time, and inside each window, each pixel individually. Each pixel can decide how to mix the previously drawn color and the color from the window.

However, maybe we could use a semi-transparent white background on the sidebar?

**Comment by BackOrder** [comment]
My idea was to go through every window underneath, save their transparency level, and tell them to be transparent and restore to the previous level when the WIN-ESC menu or Windows decorations are gone. 

> However, maybe we could use a semi-transparent white background on the sidebar?

That's up to you. This is the kind of solution all major WMs use.

**Comment by redhog** [comment]
The main problem is that it's not all windows, and not even all parts of some windows, but a narrow band over them, meaning a simple transparency parameter won't work/look good I think...
And I don't think it can be done in the shader alone, as there is only one buffer...

**Comment by BackOrder** [comment]
There is no need to make it complicated. I would absolutely make all the windows underneath transparent, not just a part of their surface but all of it. It should give a better visual experience.
