### ISSUE TITLE
Saving and restoring applications state

### ISSUE THREAD

**Issue by BackOrder** [redhog/InfiniteGlass#47]
My understanding from our multiple conversations is that saving and restoring are performed using SMLib, which is the proper approach in X but requires applications to support it.

Because not every applications support SMLib, it makes it difficult to save and restore States for any application.

I have been programming Smalltalk for many years and it always had an image to save and restore. It contains every object, live and otherwise.

Looking for something like that for Linux, I stumbled upon [CRIU](https://criu.org/Main_Page) and it seems like it could be a very good solution for InfiniteGlass.

https://www.youtube.com/playlist?list=PL86FC0XuGZPISge_th8F5Jjj-IbGXEfE6

**Comment by redhog** [comment]
Moved to https://github.com/redhog/InfiniteGlass/issues/29
