### ISSUE TITLE
Tiling again

### ISSUE THREAD

**Issue by IanTrudel** [redhog/InfiniteGlass#48]
* Tiling set selection
  * [ ] If the current window is in an island (or is an island), tile all windows in the island
  * [ ] Otherwise, tile all windows that form a connected graph of windows that are close enough to each other (less than a window width apart) where the graph contains the current window.
* [x] Zoom out so that all windows in the set are visible
* [x] Scale the windows so that they are all 1-to-1 pixel to each other
* [x] Place the windows in a "word cloud" style inside the view

The following is a set of rules tiling should follow in order to be coherent with the paradigm of InfinitGlass:

- Tiling will either use the center of the workspace or the current window focused on.
  - (I'm leaning towards the latter but it should be configurable)
- Tiling will place windows in a tag cloud style.
- Tiling will expand more horizontally (or vertically) depending on the screen orientation.
- Tiling will tile all windows, including those outside the view screen.
- Tiling should be careful when resizing and follow a logical approach:
  - Two same windows opened at a different zoom factor are actually different sizes;
  - Tiling will **flatten** all the windows to the same zoom factor and then resize to have correct proportions

![image](https://user-images.githubusercontent.com/8844578/75114155-a592eb00-5621-11ea-9d1b-a0a2bc1e0fc3.png)

![image](https://user-images.githubusercontent.com/8844578/75114099-33220b00-5621-11ea-9f68-2f3e469c34bc.png)

**Comment by redhog** [comment]
I like all the rules apart from tiling windows outside the current view - that defeats a core idea of mine of letting you build "islands" of windows for different purposes. You can always zoom out to a view where what you want to tile is visible.

Oh, you want to first resize all windows so that their pixels are 1-to-1 to each other, and then tile. That's actually much better than my current system (change pixel zoom at the end to make them 1-to-1 to screen).

**Comment by redhog** [comment]
So, for tagcloud, what's the rule? Biggest window in the center, smaller the further out you go?

Are you familiar with Jupiter Notebooks? Take a look at https://github.com/redhog/InfiniteGlass/blob/master/testing/Rectangles.ipynb where I've tested out some tiling algorithms...

Also check out https://codeincomplete.com/posts/bin-packing/ which is the algorithm I'm currently using (it's the bottom most one in the notebook above).

**Comment by BackOrder** [comment]
> I like all the rules apart from tiling windows outside the current view - that defeats a core idea of mine of letting you build "islands" of windows for different purposes. You can always zoom out to a view where what you want to tile is visible.

That's an interesting perspective. You could perhaps take a screenshot on how you usually do things? In my mind, the workspace is one and only one. Otherwise there could be two tiling shortcut: one for islands and one for the workspace. Or, yet again, perhaps we could define island zones that could be tiled inside without affecting the outside, and when tiled in the whole workspace, it would be considered as one tile and be placed accordingly.

> Oh, you want to first resize all windows so that their pixels are 1-to-1 to each other, and then tile. That's actually much better than my current system (change pixel zoom at the end to make them 1-to-1 to screen).

Yes, I think it would work really well here.

> So, for tagcloud, what's the rule? Biggest window in the center, smaller the further out you go?

No idea. It deserves some investigation. Perhaps there is already something available in Python.

> RE: Jupiter Notebooks

So cool! That might help in my study of your WM. :)

> RE: Bin-packing

Right now the tiling tiles only on one side. I had opened 10 sakura terminals and they went all on the left, one below another.

**Comment by BackOrder** [comment]
> RE: tag cloud

The best summary of the algorithm is: 

> Then finally, you start drawing the words avoiding collisions, with centre as the starting point to place the top word and then keep spiralling around with rest of the words. Converting each word into a 2D shape is what works the best.

Source: https://noeticforce.com/program-word-cloud-in-python-javascript-r-and-java

Spiral: https://stackoverflow.com/questions/22898555/how-to-write-a-spirial-function-in-python

You might be able to do this with a spiral function, Binary Tree Bin Packing and few additional rules for adjustment.

**Comment by redhog** [comment]
This is a pretty normal setup for me: Three islands: One for graphics stuff, one for development of some project (emacs, terminals, possibly browser windows with docs), one for general browsing / social media... 

![Screenshot from 2020-02-23 18-33-29](https://user-images.githubusercontent.com/104229/75116665-0f83b280-566b-11ea-9527-b041880afc1e.png)

**Comment by redhog** [comment]
This also tangles with the ghosts: You can leave the islands-setup intact over reboots, and just restart an island when you want to get back to working on that thing again. I'm even think you should be able to give the islands colors and names maybe... Like let the user draw a box around them that you can search for by name and zoom to...

**Comment by BackOrder** [comment]
The windows are clustered in such way that it would be possible to automatically determine that they are islands and apply the appropriate behaviour as suggested above. 

> This also tangles with the ghosts: You can leave the islands-setup intact over reboots, and just restart an island when you want to get back to working on that thing again. I'm even think you should be able to give the islands colors and names maybe... Like let the user draw a box around them that you can search for by name and zoom to...

Yes, absolutely. Pretty neat concept.

**Comment by redhog** [comment]
Hm, that is true, you could til only windows that are close enough to each other already....

**Comment by BackOrder** [comment]
https://github.com/rsdenijs/image_cloud/blob/master/README.md

**Comment by redhog** [comment]
Another bin packing algorithm: https://github.com/secnot/rectpack

No algorithms seem to create a proper and dense centered cloud (like a word cloud) of rectangles. The wordcloud library only works with actual words...

**Comment by IanTrudel** [comment]
Take a look at this, @redhog ! https://github.com/IanTrudel/ImageCloud

This is something that might inspire you when it comes to implementing the tiling system referred to in this issue. It's not tightly packing "windows" (here simply expressed as rectangles), but it would certainly work with some adjustments. The idea is fairly simple: sort and position the windows according to their area, width and height in a spiralling manner. The code takes into account the aspect ratio for a better viewing experience (the output is 1280x720, 16:9, in this case). 

I would have no idea where to implement this in InfinitGlass (and it's currently not in a working state on my machine at the moment, as you know).

Randomly generated rectangles:
![cloud-original](https://user-images.githubusercontent.com/8844578/181864195-d858d126-c433-43a5-8ad1-0ca02cf4ee45.png)

Redistributing the rectangles in a circle at the center of the screen:
![cloud-image](https://user-images.githubusercontent.com/8844578/181864209-1eff9856-e090-441f-b82b-17ea0685936d.png)

Finally, redistributing the rectangles in an elliptical manner at the center of the screen:
![cloud-spiral-experimental](https://user-images.githubusercontent.com/8844578/181864211-ff59b4bf-24e2-4388-a518-1a2fac5cfb25.png)

**Comment by redhog** [comment]
If you could build this as a pure python (or numpy) function that takes a list of tuples (id, w, h), one for each window, and produces another list of tuples (id, x, y), it would be pretty simple to slot it in. That way you can test it on arbitrary rectangles in a notebook together with e.g. matplotlib before you have to deal with the entirety of the window manager...

The current tiling algorithm is implemented here: https://github.com/redhog/InfiniteGlass/blob/master/glass-input/glass_input/actions/tile.py#L7 , so the new one would have to eventually be wrapped in the same manner...

**Comment by IanTrudel** [comment]
Yes, absolutely. My understanding is that it would be as simple as writing a replacement to the GrowingPacker class?

**Comment by redhog** [comment]
Yes exactly :) If it has a similar API, slotting it in gets trivial!

**Comment by IanTrudel** [comment]
There you go! You will find a CloudPacker class at https://github.com/IanTrudel/ImageCloud/blob/master/cloud_packer.py and a Jupyter Notebook with tests at https://github.com/IanTrudel/ImageCloud/blob/master/cloud_packer.ipynb.

It's pretty close to what is already in InfiniteGlass. One change is that I removed the GrowingPacker structure with named parameters to better fit into InfiniteGlass without having to do conversions.

There are plenty of improvements to make, but this should be an interesting starter kit. :)

![Capture d’écran du 2022-07-30 17-27-53](https://user-images.githubusercontent.com/8844578/181996717-d815b19c-48cd-4ac0-b9ea-7d7079140b7b.png)

**Comment by redhog** [comment]
Cool! I'll give it a try soon!
How is the spacing between windows controlled? It seems like it's mostly the same, except your light blue one in the image above is way closer to the dark one below it, and also the one to the lower left, isn't slid as far as it can to the right (but that might be an artefact of the algorithm)?

**Comment by redhog** [comment]
I just added this to InfiniteGlass: https://github.com/redhog/InfiniteGlass/commit/b0565e27a57ba3a9890e4b46879ebcf920731544
You use it by WINDOWS+O (and WINDOWS+SHIFT+O for non zooming version). The old algorithm is still available on WINDOWS+T for comparison.

It seems buggy though. I made three terminal windows, and they end up along the edges, and really small...

**Comment by redhog** [comment]
Here is an example of some blocks that fail:

```
cloud_packer_test_blocks([{'w': 0.655937511920929, 'h': 0.37781252384185793, 'window': 14680070},
  {'w': 0.655937511920929, 'h': 0.37781252384185793, 'window': 14680116},
  {'w': 0.5278125, 'h': 0.410625, 'window': 20971652}], view_width=1.0, view_height=0.6000000238418579)
```

(see https://github.com/redhog/InfiniteGlass/blob/master/testing/cloud_packer.ipynb for details)

I first thought it was about the margin, but setting the margin to something low does not fix the problem.

**Comment by IanTrudel** [comment]
There are many challenges to testing outside InfiniteGlass. Everything has been tested in one quadrant, and InfiniteGlass is supposed to have an infinite amount of surfaces on a canvas to draw on, with a view screen. It might be difficult for me to fix it until I can test myself. You could provide some data in a file though (windows, view, and whatever else would make a good case for InfiniteGlass).

The algorithm is fairly simple: it places the first window in the middle of the viewing area, and the other windows are placed in a spiralling manner. It spirals until it finds a non-intersecting position. It would probably be better to increase the radius instead of theta until it finds a place, and then reset the radius and increase theta, repeat. I suspect it would result in better packing and a more elegant one at that.

> spiral = self.spiral_generator(20, 1.5)

You may want to play around with these parameters to yield better results. I changed them until the result looked reasonable according to IMAGE_WIDTH, IMAGE_HEIGHT and ASPECT_RATIO.

Thank you for testing! So cool!

**Comment by IanTrudel** [comment]
Another idea would also be to break down the spiral into segments, e.g. `step = (360 / number of windows)`, according to the number of windows, which would cause the windows to be evenly spread around the central window. If the number of windows exceeds a certain threshold, we could off balance the segments on multiple layers (offsetting the radius even more).

**Comment by redhog** [comment]
Hm, it should be pretty easy to to test it outside infinite glass:

Matplotlib can plot any size rectangles using patches

```
      ax.add_patch(
          Rectangle(
              (shape["fit"]["x"], shape["fit"]["y"]),
              shape["w"], shape["h"],
              edgecolor=color, color=color, alpha=0.5))
```

Just make sure to update xlim/ylim manually at the end. That is, do away with your whole PIL based plotting, and just let matplotlib handle scaling the drawing area...

More concerning though is to generate a realistic set of window sizes. The purely random generation you have often gives very tall or wide windows, and I don't think the failure modes of any tiling algorithm exercised by this are very interesting...

**Comment by redhog** [comment]
Note however, that aspect ratio is still important: I'd test w something realistic for your screen.
Note that in the IG code around the tiler, there is an optional extra last step, that zooms to the tiled windows so that their bbox covers the screen as well as possible.

**Comment by IanTrudel** [comment]
> More concerning though is to generate a realistic set of window sizes. The purely random generation you have often gives very tall or wide windows, and I don't think the failure modes of any tiling algorithm exercised by this are very interesting...

Agreed. Do you know how to list all the current windows displayed on X in Python? I could build a list from my own usage and update it frequently, build a database of sort to test with.

**Comment by IanTrudel** [comment]
I managed my way to list all visible windows and move them in Xephyr using `python-xlib`. Should be good enough to experiment while you find a solution for #89. :P 

Does InfiniteGlass have its own window for each window? I noticed that the window decorations in twm are contained in a window and the applications, such as xterm, is a child of that window. So either I test with this minimalistic WM or without.

**Comment by IanTrudel** [comment]
Hmmm. I added support for margins, seems to help a bit. You are correct that tall windows and other factors such as having many windows and overflowing the resolution mess up the algorithm. It's doing not too bad though, there is potential. Any way to have a virtual resolution with Xephyr? It's hard to reproduce an infinite desktop. :)

Check ImageCloud repository. I updated CloudPacker to take margins into account. There is also a script to pack windows within Xephyr. 

![Capture d’écran du 2022-08-01 00-12-09](https://user-images.githubusercontent.com/8844578/182070916-e1431963-6b29-47f5-9d19-548149873cc7.png)

![Capture d’écran du 2022-08-01 00-13-29](https://user-images.githubusercontent.com/8844578/182070922-a3891d91-21a8-4cb8-ba49-eb682f390116.png)

**Comment by IanTrudel** [comment]
![Capture d’écran du 2022-08-01 01-36-08](https://user-images.githubusercontent.com/8844578/182079192-b70875cb-1110-4fd2-83aa-48aef57672b7.png)

**Comment by redhog** [comment]
Check out this function in the command line utility glass-action that does just that:
https://github.com/redhog/InfiniteGlass/blob/master/glass-action/glass_action/window.py#L27

**Comment by redhog** [comment]
Btw: import InfiniteGlass / glass-lib is a wrapper around python-xlib that makes it have a slightly nicer syntax, esp for properties, and some utility functions, see function above.

I'd ignore all integer examples with real screen coords, and just go with matplotlib so your width/height can be whatever (0.03 or 400032.47), but both for the screen and the windows, make sure their aspect ratios are realistic (as per your measured values from real windows).

As for decorations, InfiniteGlass does not add a wrapper window around each window like TWM does. Decorations are drawn differently in IG (mostly pure shader code stuff).

**Comment by IanTrudel** [comment]
Thank you for the reference on how to get visible windows. I managed to write a script to collect the information, even create windows and so on.

Though it's challenging because I'm running on multiple monitors with different resolutions. The resulting data is hardly usable at the moment.

Is there a way to distinguish a window displayed on one monitor versus another monitor? I could be able to attach the resolution for each record in the database and resize according to the test environment.

Using matplotlib has a few downsides:

- It's not interactive. Xephyr allows me to move, resize, minimize, open and close windows; and, then, running the cloud packing. Useful is an understatement.
- Matplotlib coordinates are different from X/InfiniteGlass. The latter has (0, 0) on top left side whereas Matplotlib has the starting point at the bottom left side.
- Testing is faster with Xephyr. Results are immediate. It can also be left open for testing at a later time. Since I can create arbitrary windows from Python..

Seems like Xephyr and `python-xlib` are the better choice here unless you have counter arguments.

**Comment by redhog** [comment]
New tiler that does this:

![image](https://user-images.githubusercontent.com/104229/182701382-b96e96f2-7da8-48b5-9709-c1504a6f8557.png)

It is based on your code, but with some important changes:

* It uses a binary search instead of a progression of angles/radii
* It adjusts a fitted position inwards first along x, then along y, again using a binary search

**Comment by redhog** [comment]
Here's what it does for only 5 windows:

![image](https://user-images.githubusercontent.com/104229/182702467-8c5f1772-6260-4d0b-8881-3246ecd1959e.png)

**Comment by redhog** [comment]
It is scale invariant, handles the aspect ratio, does not ever overlap windows, and usually gives a pretty tight packing. It's reasonably fast.

**Comment by redhog** [comment]
Btw: I'll be on vacation the next two weeks, so will be offline.

**Comment by IanTrudel** [comment]
It seems like something that would indeed perform better. It's hard to beat a binary search. Any way to reshuffle a bit to avoid holes? Fine-tuning is where we could really make a difference as far as tiling goes; for example, the 5 windows example would probably look better if the slim but tall window were swapped with the grey-pinkish larger window. Remember to leave the code somewhere, so I can take a look while you are on vacation!

> Btw: I'll be on vacation the next two weeks, so will be offline.

Does it mean sitting at home with the WiFi off? :)

**Comment by redhog** [comment]
New code is here: https://github.com/redhog/InfiniteGlass/blob/master/glass-input/glass_input/cloud_packer.py
You can test it in isolation using this notebook: https://github.com/redhog/InfiniteGlass/blob/master/testing/cloud_packer.ipynb

**Comment by redhog** [comment]
Nah, means I'll be in the UK walking around lakes, laptopless...

**Comment by IanTrudel** [comment]
Thank you! I enjoy presenting you with ideas and a bit of code, and you dive in and come up with your own approach. Bouncing back and forth is quite productive and intellectually stimulating. Hope you will enjoy the UK!

**Comment by IanTrudel** [comment]
> New code is here: https://github.com/redhog/InfiniteGlass/blob/master/glass-input/glass_input/cloud_packer.py You can test it in isolation using this notebook: https://github.com/redhog/InfiniteGlass/blob/master/testing/cloud_packer.ipynb

`from glass_input.cloud_packer2 import CloudPacker2` nowhere to be found on the repo.

**Comment by redhog** [comment]
That import was just testing stuff I forgot to delete, and isn't used. I have pushed a new version where that line is removed...

**Comment by redhog** [comment]
Gonna close this as we now have two fairly ok tiling algorithms implemented.

**Comment by IanTrudel** [comment]
I couldn't test much until you had a docker image running but, while it is not exactly how I envisioned it, it is indeed fairly ok. Something that can easily be revisited at a later time. Thank you for integrating this into InfiniteGlass!
