### ISSUE TITLE
Strange square

### ISSUE THREAD

**Issue by BackOrder** [redhog/InfiniteGlass#49]
I'm getting a strange square when starting up the WM since the last git pull. It cannot be moved, resized, WIN-C, etc.

![image](https://user-images.githubusercontent.com/8844578/75115444-a11fff80-562c-11ea-94dc-c420563a84d2.png)

**Comment by redhog** [comment]
Can you still run other apps normally?

**Comment by BackOrder** [comment]
Yes, no. It's unclear. I had some troubles during testing. Do I need to delete some things in ~/.config/glass ?

**Comment by redhog** [comment]
Well, delete at least ghosts.sqlite3...

**Comment by redhog** [comment]
If you're comfortable with git, you can always make ~/.config/glass a git repo and add all files except the sqlite file, and then when you upgrade you can always delete the files so they are recreated and see the diff...

**Comment by BackOrder** [comment]
Deleting `ghosts.sqlite3` did the trick. :)
