### ISSUE TITLE
Fractal background

### ISSUE THREAD

**Issue by redhog** [redhog/InfiniteGlass#50]
https://github.com/danilobellini/fractal

**Comment by BackOrder** [comment]
The fractal library should be easy enough to integrate in InfiniteGlass. The function `generate_fractal` returns an image that you can display. Might even be possible to animate or change every T amount of time, if animation is too slow.

**Comment by BackOrder** [comment]
![2ruajbahank41-45](https://user-images.githubusercontent.com/8844578/75934211-e53fab00-5e49-11ea-9776-f7bb2ed6aaf1.gif)

https://www.reddit.com/r/math/comments/fdc0zc/fractals_from_an_iterated_function_system_oc/

https://github.com/earlbellinger/fractals

**Comment by redhog** [comment]
That is super cool! I wonder which of these could be implemented purely in the fragment shader?

**Comment by BackOrder** [comment]
Is there a Python to GLSL converter/generator? That would be something useful.

**Comment by redhog** [comment]
I don't think so, and there's another thing: GLSL shaders have a quite... interesting processing model.

In short, the pipeline works like this:

* C code sends a bunch of arrays and a bunch of scalars, called uniforms, and a bunch of images (textures). All shader code has access to the uniform values and the textures all the time.
* Vertex shader gets a row of data containing one value from each array, and outputs a new row of data.
* The geometry shader gets a row of data from the vertex shader, and outputs any number of rows of data.
  * Here, each row needs to have a coordinate, and a drawing mode specifies how many rows together make up a shape: points take just one row, lines two, triangles three etc.
* Across the shape, the values in the (two for lines, three for triangles) rows are interpolated based on distance.
* For each pixel, the fragment shader gets a row of interpolated values and produces a color.

You can do a lot of weird and cool stuff in the fragment shader - but it has to be sort of "local" - it can not output more than one pixel, and it can not read the output of other pixels. But it does know its own coordinate, and it can access textures to look up values at some coordinate in those textures.

**Comment by BackOrder** [comment]
This one should be a good starting point. https://github.com/neozhaoliang/pywonderland/blob/master/src/fractal3d/fractal3d.py

**Comment by redhog** [comment]
Oh cooooool!

**Comment by alexkh** [comment]
Here's my OpenGL version of Lyapunov fractal that I found on my hard drive: https://github.com/alexkh/gllyap

**Comment by redhog** [comment]
Cool! That looks awesome! I think I might spend some time on this once islands are done maybe...

**Comment by alexkh** [comment]
k, Lyapunov background seems to be working. I only changed one file: glass-theme/glass_theme/shaders/root/fragment.glsl https://github.com/alexkh/InfiniteGlass/commit/7a7e7637e4b9111a1efeeddccba6b1a926fbf975#diff-5984784349a72c05728c803f0f50663d

**Comment by BackOrder** [comment]
![image](https://user-images.githubusercontent.com/8844578/77012574-96633c80-6944-11ea-8cd5-f28f17474bcf.png)

**Comment by redhog** [comment]
This is fantastic @alexkh !!!

**Comment by BackOrder** [comment]
@redhog hold your breath, I asked him if he could make it configurable and animated. Ah!

**Comment by redhog** [comment]
Should not have closed this, as we might want to experiment with other fractals too?

**Comment by alexkh** [comment]
Btw, Lyapunov fractal has that special parameter: it will give quite different pictures depending on the pattern of permutations. If you look closely at this part of the code:
 for (int i = 0; i < FRACTAL_PRECISION; i++) {
    x = w1*p.x*x*(1.0-x); h += log2(abs(w1*p.x*(1.0-2.0*x)));
    x = w2*p.x*x*(1.0-x); h += log2(abs(w2*p.x*(1.0-2.0*x)));
    x = w3*p.y*x*(1.0-x); h += log2(abs(w3*p.y*(1.0-2.0*x)));
    x = w4*p.x*x*(1.0-x); h += log2(abs(w4*p.x*(1.0-2.0*x)));
    x = w5*p.y*x*(1.0-x); h += log2(abs(w5*p.y*(1.0-2.0*x)));
  }
you'll notice that this particular fractal has classical pattern AABAB. The difference between lines is whether x or y of the point is used in the permutation. This particular fractal is featured in all tutorials and in Wikipedia: https://en.wikipedia.org/wiki/Lyapunov_fractal
But there can be a huge variety of patterns giving different results. I'm not even sure what would be the optimal way to implement the ability to specify the pattern in InfiniteGlass settings. Also, it might be cool to set initial center and zoom level, no?

**Comment by redhog** [comment]
Interesting. I had never seen this type of fractal before *went and read up on it on wikipedia*

Cool. You do something slightly differently from wikipedia though, where you set r_n not to a or b, but to some fraction of them?

**Comment by alexkh** [comment]
I'm getting black screen and need to switch to another terminal and type killall -9 Xorg to exit when I try to set my ~/.config/glass/theme.json to:
{
    "name": "glass_theme.default.Theme",
    "args": {
        "latlon": [70., 18.],
	"mode": "no_splash",
	"define_BACKGROUND_TYPE": 1,
	"define_FRACTAL_PRECISION": 100,
	"define_BACKGROUND_COLOR_TRANSFORM":
		"transpose(mat4(0.0, 0.0, 0.0, 1.0,  -0.5, 0.0, 0.0, 1.0,  -0.5, 0.0, 0.0, 1.0,  0.0, 0.0, 0.0, 1.0))"
    }
}

Is there a way to assign Ctrl-Alt-Backspace to exit InfiniteGlass? At least that'd simplify debugging a bit...

**Comment by redhog** [comment]
Btw, since the fractal doesn't really extend infinitely, maybe we could make it repeat after X units in each direction, but with a different parameter?

**Comment by redhog** [comment]
Not at all. Bind whatever keybinding you want in input.json to "send_exit".

**Comment by redhog** [comment]
Do you get any interesting output on stderr/stdout of glass-ghosts / the whole session when this happens?

Any shader compile errors should dump stuff there... And so should any OpenGL error...

**Comment by alexkh** [comment]
> Interesting. I had never seen this type of fractal before _went and read up on it on wikipedia_
> 
> Cool. You do something slightly differently from wikipedia though, where you set r_n not to a or b, but to some fraction of them?

I probably took that fractal from Shadertoy, I used it just to test my OpenGL init code back in the days. It might be modified, but I guess the same configuration princible applies. Don't forget: we can scale it up and it will be more "infinite", no?

**Comment by redhog** [comment]
True... But there are large fairly homogenous areas (at least if your N iterations isn't large enough)

**Comment by redhog** [comment]
I think I should give you free reign to experiment with this. We can easily have multiple backgrounds / presets to chose from...

**Comment by alexkh** [comment]
Technically, any fractal is limited in space, and they all require tons of iterations to give pretty results...

**Comment by alexkh** [comment]
Even this gives me black screen, and it does not even show the splash:
{
    "name": "glass_theme.default.Theme",
    "args": {
        "latlon": [70., 18.],
	"define_BACKGROUND_TYPE": 1
    }
}

**Comment by redhog** [comment]
On latest master? Works for me... Do you run InfiniteGlass with "make"?

**Comment by redhog** [comment]
That's why I'm proposing we do

    x = p.x % 5.;
    y = p.y % 5.;
    w4 = sin(0.1 * floor(p.x / 5));
    w5 = sin(0.1 * floor(p.y / 5));

or something along those lines...

**Comment by alexkh** [comment]
no, i run it with "startx"

**Comment by BackOrder** [comment]
You can also reload glass-theme using:

`glass-action component restart glass-theme`

**Comment by redhog** [comment]
Aha. Then you should have stderr/out in ~/.glass.log, check that file and see what it has dumped there...

**Comment by alexkh** [comment]
K, I figured it out: the json parser does not tolerate tab character, which is weird. Also, instead of giving up and moving on, it enters an infinite loop trying to re-read the config file, which is also kinda weird.

> yaml.scanner.ScannerError: while scanning for the next token
> found character '\t' that cannot start any token
>   in "/home/sv/.config/glass/theme.json", line 5, column 1
>

**Comment by redhog** [comment]
It's not an infinite loop actually: The component (glass-theme) exits with a non-zero exit code (that's what python does on an exception if there is no exception handler catching it), and glass-ghosts will restart any component that fails this way. It's a bit stupid when it happens on start-up, but for things like glass-input, if it happens in the middle of your session because say a function you bound to a key crashes it, it makes sense to just get it back up so your whole session doesn't screw up for you...

**Comment by redhog** [comment]
Also, the config files are parsed by a yaml parser. They are all JSON, but I use a yaml parser so that you can embed comments in them - I felt like example config files / templates without comments are pretty useless...

**Comment by alexkh** [comment]
If you want to see the animation, i made a shadertoy version: https://www.shadertoy.com/view/WdscWH

**Comment by BackOrder** [comment]
It's quite disturbing. Good job. :tada:

**Comment by alexkh** [comment]
Check out JSON5, I think it's the way to go for config files: https://json5.org/

**Comment by BackOrder** [comment]
https://pypi.org/project/json5/ for Python programming.

**Comment by redhog** [comment]
Hm, maybe we do need animated drawing like that. It looks super surealistic!

**Comment by redhog** [comment]
Moved the config language (JSON5) stuff to https://github.com/redhog/InfiniteGlass/issues/70

**Comment by redhog** [comment]
Btw, shadertoy seems like a really good tool for experimenting with this easily :)

**Comment by alexkh** [comment]
Just found out that the static shader's author is Inigo Quiles (creator of Shadertoy) himself, so we must credit him in the shader code. I still have no Idea who added animation to it, so for now les't just state:

// Original code author: Inigo Quilez 2013 https://www.shadertoy.com/view/Mds3R8
// Animation: author unknown :-(

**Comment by redhog** [comment]
I have contacted him with a DM on twitter to clear up the attribution and licensing stuff.

**Comment by BackOrder** [comment]
> Just found out that the static shader's author is Inigo Quiles (creator of Shadertoy) himself, so we must credit him in the shader code. I still have no Idea who added animation to it, so for now les't just state:

> // Original code author: Inigo Quilez 2013 https://www.shadertoy.com/view/Mds3R8
> // Animation: author unknown :-(

@alexkh Absolutely honourable thing you did here. Keep it up!

**Comment by alexkh** [comment]
a little bug in the shader:
h /= 200.0 * 5.0;
should be:
h /= FRACTAL_PRECISION * 5.0;

**Comment by BackOrder** [comment]
![](https://i.imgur.com/0pc0fcZ.jpg)

**Comment by redhog** [comment]
Oh, that's really pretty!

**Comment by BackOrder** [comment]
![](https://i.imgur.com/aYo0HdG.jpg)

**Comment by BackOrder** [comment]
So much blink.

**Comment by BackOrder** [comment]
This one is worth sharing. https://www.reddit.com/r/Unity3D/comments/fo334b/magnetic_fields

**Comment by BackOrder** [comment]
[On Reddit](https://www.reddit.com/r/glsl/comments/fox4j4/mandelbrot_set_pixilation_issue)

![](https://i.imgur.com/FStCYkV.png)

**Comment by redhog** [comment]
Licensed version of the above mandelbrot code: https://github.com/WebManifestation/mandelbrot-GLSL
