### ISSUE TITLE
Window decorations 2

### ISSUE THREAD

**Issue by redhog** [redhog/InfiniteGlass#54]
* [x] Framework for toggling symbols
* [x] Make the pin work (turn on/off shadows for this window)
* [x] Don't show decorations for too small / zoomed out windows
  * [x] Only show decorations for window close to mouse?
* [x] ![font-awesome_4-7-0_times-circle_20_0_007dff_none](https://user-images.githubusercontent.com/104229/76116695-c298c800-5fea-11ea-8e84-f0aca0e17630.png) - close
* [x] ![font-awesome_4-7-0_save_20_0_007dff_none](https://user-images.githubusercontent.com/104229/76113103-cbd26680-5fe3-11ea-888a-130e39a1d483.png) / same filled in - turn on / off ghosts for this window
* [x] ![font-awesome_4-7-0_play-circle-o_20_0_007dff_none](https://user-images.githubusercontent.com/104229/76113205-ff14f580-5fe3-11ea-935b-dca64df9082e.png) / ![font-awesome_4-7-0_pause-circle-o_20_0_007dff_none](https://user-images.githubusercontent.com/104229/76113218-04724000-5fe4-11ea-9dbb-3f5320927042.png) - save / restore the app 
* [x] ![foundation-icon-fonts_2015-02-16_monitor_20_0_007dff_none](https://user-images.githubusercontent.com/104229/76113414-616df600-5fe4-11ea-8a31-0cca11216dd3.png) - toggle full screen
* [ ] ![material-icons_3-0-1_more-horiz_20_0_007dff_none](https://user-images.githubusercontent.com/104229/76115109-d7279100-5fe7-11ea-844c-e9e8b85fb1c8.png) - submenu with more widgets
  * [ ] ![font-awesome_4-7-0_cog_20_0_007dff_none](https://user-images.githubusercontent.com/104229/76114868-52d50e00-5fe7-11ea-924e-29e3a223f10d.png) - Configure further settings
  * [ ] ![font-awesome_4-7-0_lock_20_0_007dff_none](https://user-images.githubusercontent.com/104229/76112686-f839b300-5fe2-11ea-81d3-1d7afc874016.png) / ![font-awesome_4-7-0_unlock_20_0_007dff_none](https://user-images.githubusercontent.com/104229/76112637-dc361180-5fe2-11ea-8e29-fe81309f4168.png) - lock/unlock window in place (e.g. for tiling)
  * [ ] ![material-icons_3-0-1_volume-down_20_0_007dff_none](https://user-images.githubusercontent.com/104229/76116426-42726280-5fea-11ea-8c8b-c6356aa8a877.png) / ![material-icons_3-0-1_volume-up_20_0_007dff_none](https://user-images.githubusercontent.com/104229/76116438-48684380-5fea-11ea-8419-7c79ad3ee1ff.png) / ![material-icons_3-0-1_volume-off_20_0_007dff_none](https://user-images.githubusercontent.com/104229/76116499-6635a880-5fea-11ea-92ca-eef2e1f58301.png) - Volume down, up, turn on/off

**Comment by BackOrder** [comment]
Is the recent merge includes actual window decorations to test? I can test tonight!

**Comment by redhog** [comment]
Yep it does. You need to clear/update ~/.config/glass/widgets.json

**Comment by BackOrder** [comment]
I'm so excited!

:raising_hand: << vim user.

**Comment by redhog** [comment]
Btw, did you find out anything regarding svg rendering and skia?

**Comment by BackOrder** [comment]
My docket is full this week. Nothing beyond reading Skia documentation.

**Comment by BackOrder** [comment]
![image](https://user-images.githubusercontent.com/8844578/76038539-d1fb1100-5f17-11ea-8701-8c0d32fcbb6f.png)

This is fun! Great work!

Pin and save respond to clicks

```
b'Terminal'/b'Pin'.()
b'Terminal'/b'Save'.send_sleep()
XXXXXXXXXXXXXXXXX SLEEP <class 'Xlib.display.Window'>(0x01a00006) b'Terminal'
```

Close is working but there is an **Xlib.error.BadWindow**

```
b'Terminal'/b'Close'.send_close()
XXXXXXXXXXXXXXXXX CLOSE <class 'Xlib.display.Window'>(0x01a00006) b'Terminal'
b'Terminal'/b'Close'.send_close()
XXXXXXXXXXXXXXXXX CLOSE <class 'Xlib.display.Window'>(0x00400015) b'Terminal'
X protocol error:
<class 'Xlib.error.BadWindow'>: code = 3, resource_id = <class 'Xlib.xobject.resource.Resource'>(0x00400015), sequence_number = 10141, major_opcode = 4, minor_opcode = 0
```

Also, I'm expecting close to fully close (without shadow) and pause to put to sleep.

![image](https://user-images.githubusercontent.com/8844578/76038829-a2003d80-5f18-11ea-92d2-885e1fa48238.png)

Might be necessary to resize the buttons as well. :))) Default should be a bit smaller too.

Keep it up! It's super satisfying!

**Comment by redhog** [comment]
So save closes and saves the whole app. Close closes a single window. 

So there are some alternatives:

* close closes a window but never leaves a shadow - means toolboxes and the like can't be laid out with shadows, maybe not such a big use-case?
* close leaves shadows _if_ the pin marker is not  unpinned
* should this work differently on the main app window and subwindows (if that's possible to detect properly), e.g. maybe the save button is "close with shadow" on subwindows, and "save app" only on the main window?

And a problem:

* What do we do if _all_ windows of an app are unpinned when the user presses save? How can the user restart the app? Should we hide the save button in that case, or forbid unpinning the last window of the app?

**Comment by BackOrder** [comment]
> Font awesome does not have these two symbols. Where to find?

Are you using fonts for window decorations? This will be a problem for theming InfiniteGlass. SVG icons are the best option.

> Only show decorations for window close to mouse?

Yes, please! One thing about your WM is that it's unencumbered and allows more space for actual content.

Also, my suggestion is that the window decorations appear on the corner closest to the mouse to keep travel distance to a minimum.

> RE: Pinning

I'm bit lost when it comes to the concept. My initial thought was that pinning would prevent the window from moving, especially in case of tiling. Tiling could work other windows around but keep the pinned ones exactly where they are.

> RE: Close

Do you have Gimp in mind? Close should close the window but when every windows of a given app are closed, the app should terminate.

Also, shadows don't need window decorations.

> RE: Saving apps, closing and such

There could be general preferences where one could say close either means close or it means saving. One thing I absolutely dislike on Windows is close often mean hide in the tray instead of quitting.

> ...

Universal symbol for additional options where other icons could be displayed to do whatever else you think is necessary but not absolutely necessary. For example, volume control for individual apps would be nice but it would clutter the window decorations. It would fit better in a ... icons (just like a submenu).

> RE: Sleeping

Would it be possible to have a thumbnail added to the shadow window? A screenshot of the app on save.

Pause/play button is not immediately obvious but it does fit InfiniteGlass paradigm.

**Comment by redhog** [comment]
> Are you using fonts for window decorations? This will be a problem for theming InfiniteGlass. SVG icons are the best option.

No, I use SVG, but the symbols in  fontawesome come as a set of SVG:s too. That's what I use....

>> RE: Pinning
> I'm bit lost when it comes to the concept. My initial thought was that pinning would prevent the window from moving, especially in case of tiling. Tiling could work other windows around but keep the pinned ones exactly where they are.

So this actually came out of our discussion about ghosts, where you wanted to be able to configure individual apps/windows to (not) leave ghosts... I thought that since ghosts means that windows are kind of pinned to a place even when they're dead and reappear at that place, a pin would make sens for this, but maybe some other symbol would be better? Maybe something that symbolises immortality?

> Do you have Gimp in mind? Close should close the window but when every windows of a given app are closed, the app should terminate.

Yep, GIMP is a very good example. Millions of little toolbox windows all over the place....

> One thing I absolutely dislike on Windows is close often mean hide in the tray instead of quitting.

Yeah, that is super-annoying. Happens on Linux too with skype. How do you even quit such an app? The thing with save in InfiniteGlass is that it really isn't invisible - the ghosts are big and obvious, and you can use their close button to kill them off.

> ...

Universal symbol for additional options where other icons could be displayed to do whatever else you think is necessary but not absolutely necessary. For example, volume control for individual apps would be nice but it would clutter the window decorations. It would fit better in a ... icons (just like a submenu).

Oh, that's a cool feature. No idea how easy it is to implement, but it would be super useful. And that reminds me of another feature I'd like to add: Showing visually which window is currently a sound source....

> Would it be possible to have a thumbnail added to the shadow window? A screenshot of the app on save.

It is. The icon of the app is trivial, screenshot requires a little more work, but not that much I think...

**Comment by redhog** [comment]
You could play around with different icons in widgets.json btw, maybe you come up with some really smart symbolisms?

**Comment by BackOrder** [comment]
> RE: discussion on ghosts

My initial suggestion was a cog to set window individual preferences. We should also have system-wide preferences. How easy would it be to write a Python GUI interfacing with existing InfiniteGlass libraries?

> RE: Quitting Skype

Don't install it in the first place? :) :) :)

> Showing visually which window is currently a sound source....

Oh yes! That would be great.

> You could play around with different icons in widgets.json btw, maybe you come up with some really smart symbolisms?

So far we have talked about : 

* X symbol for close
* Plus sign for maximize
* Minus sign for minimize
* Cog for preferences
* Ellipsis (...) for additional decorations
  * Volume up, down, turn on/off
  * Pin symbol for... (see more below)

> RE: Plus and minus sign

Minimizing a non-fullscreen window doesn't make much sense in InfiniteGlass, does it? It would be better to display only the maximize icon in windowed mode and display a minimize icon in fullscreen.

> RE: Pin symbol

I'm really liking the idea of being able to pin (as in stick a window in place) a window where it would prevent retiling. It would reinforce the idea of islands and make it easier to tile other windows around one or more windows.

> RE: fullscreen window decorations

This is a difficult one. Moving the mouse to a corner and having window decorations overlay might prevent using some features in any given app. What about having one of your magic shortcuts to pop up window decorations? Also, InfiniteGlass should override Xorg default right click menu anyway where we could add the decorations along. Got a few ideas, let me get back to you on this one.

**Comment by redhog** [comment]
Some symbol proposals in addition to yours above / replacing some of them:

* ![font-awesome_4-7-0_lock_20_0_007dff_none](https://user-images.githubusercontent.com/104229/76112686-f839b300-5fe2-11ea-81d3-1d7afc874016.png) / ![font-awesome_4-7-0_unlock_20_0_007dff_none](https://user-images.githubusercontent.com/104229/76112637-dc361180-5fe2-11ea-8e29-fe81309f4168.png) - lock/unlock window in place (e.g. for tiling)
* ![font-awesome_4-7-0_save_20_0_007dff_none](https://user-images.githubusercontent.com/104229/76113103-cbd26680-5fe3-11ea-888a-130e39a1d483.png) / same filled in - turn on / off ghosts for this window
* ![font-awesome_4-7-0_play-circle-o_20_0_007dff_none](https://user-images.githubusercontent.com/104229/76113205-ff14f580-5fe3-11ea-935b-dca64df9082e.png) / ![font-awesome_4-7-0_pause-circle-o_20_0_007dff_none](https://user-images.githubusercontent.com/104229/76113218-04724000-5fe4-11ea-9dbb-3f5320927042.png) - save / restore the app 
* ![foundation-icon-fonts_2015-02-16_monitor_20_0_007dff_none](https://user-images.githubusercontent.com/104229/76113414-616df600-5fe4-11ea-8a31-0cca11216dd3.png) - toggle full screen

So... I guess renaming your "pin" option to "lock", and my "pin" to "save location"?

**Comment by redhog** [comment]
Btw, minimize doesn't really make sense at all - a window morphs into its icon when you zoom out enough that it's too small to show the content.. But conceptually that's not iconification - the window hasn't changed, it's not in a different mode, you're just too far away to see it properly...

**Comment by BackOrder** [comment]
Yes! Yes! These would be perfect. Even the colour would be good.

> So... I guess renaming your "pin" option to "lock", and my "pin" to "save location"?

Agreed.

> RE: Other icons

Do you have a cog and ellipsis somewhere? Pretty sure we need them too.

> RE: Minimize

Indeed. Toggle full screen is what makes sense.

**Comment by redhog** [comment]
I'm using the fonts here: http://fa2png.io/fonts/

**Comment by redhog** [comment]
Added those two. But right now I'm not sure what would end up under ..., but I'm sure we'll come up with loads of stuff eventually...

**Comment by BackOrder** [comment]
![InfiniteGlassUIConcept](https://user-images.githubusercontent.com/8844578/76135831-bd427a00-5ff8-11ea-8c9d-0dc70aa2a32a.gif)

**Comment by BackOrder** [comment]
The window decorations are supposed to reduce opacity as you move from one to another. It's also a bit too fast. I'm using a new software for the animation, learning along the way. Hopefully it inspires you anyway.  :)

**Comment by redhog** [comment]
Cool, that looks really sleek. And if you have animation software to play around in - keep experimenting! I have to do everything "the hard way", so it takes longer time for me...
I would offset the secondary icons a bit more though, so that they don't overlap...

**Comment by BackOrder** [comment]
> Cool, that looks really sleek. And if you have animation software to play around in - keep experimenting! I have to do everything "the hard way", so it takes longer time for me...

Yes, sir! The software is super intuitive to use for prototyping such kind of things. The best I used so far. I will keep experimenting but if you have ideas you want me to do, let me know.

> I would offset the secondary icons a bit more though, so that they don't overlap...

Indeed, it would be better. My concern is travel distance. I have a slightly different take on the same concept. I will show you when it's done. :)

**Comment by BackOrder** [comment]
![InfiniteGlassUIConcept-MenuWorkflow](https://user-images.githubusercontent.com/8844578/76169441-8a11ff00-614e-11ea-9422-e51678e5d471.gif)

This is the new concept for the window decorations. Don't mind the line, it's a reference for you to be able to see the cursor move. 

* The core idea is to minimize travel distance.
* Clicking will produce the next menu (here, in this example, system menu and then volume menu).
* Moving the mouse either way will either backward to the previous menu or forward to the next menu, like mouse buttons would do on a web browser.

Additional ideas:
* Mouse over will increase the size of the icon so the user knows it is selected.
* Vertical mouse movements will move the icons up or down, if you like that kind of stuff.
* Vertical mouse movements will rotate the icons from top to bottom or bottom to top depending on the case.
* Mouse wheel will scroll through the icons and rotate them from top to bottom or bottom to t op. (On the spot idea, sounds fantastic!)

**Comment by redhog** [comment]
I like the scroll-wheel idea... and the mouse move means select/go back is interesting, but I'd have to try it to see how it feels...

**Comment by BackOrder** [comment]
At least having a visual reference now really helps. We will what we keep and what we discard once we get something to play with. :)

**Comment by BackOrder** [comment]
> I like the scroll-wheel idea... and the mouse move means select/go back is interesting, but I'd have to try it to see how it feels... 

If there's an argument for it, all major WM (incl. Windows and macOS) waste a lot of our time on fancy things, mouse movements and lots of clicking or shortcuts. This is something InfiniteGlass can do better, whatever the solution will be.

Perhaps it explains why some people like tiling window managers. I find them super stiff to use but it doesn't take away the practicality they have.

**Comment by redhog** [comment]
Yeah, I'm all for rethinking each problem "from scratch"! I started InfiniteGlass because I felt like my current WM didn't support my workflow very well. In my workflow, I don't really need non-maximized windows, but I need the other (currently non-visible) workspaces to be organized in a way I can remember intuitively. That's also why I liked your edge-hinting thing...

And yes, I'm the same about tiling...

**Comment by redhog** [comment]
Ping @BackOrder : Just so you know, I'm a bit stuck on fixing a serious bug on this issue, that's why I'm not doing any other features for now... it'll take a while :(

The bug: Something is screwed up with textures, so that when a window has multiple textures, all end up containing the same image!! And I've been digging and digging and I can't figure out why!

**Comment by redhog** [comment]
I'm an idiot.

When generating textures, you bind them. To the current texture unit. Whatever that is....

**Comment by BackOrder** [comment]
> I'm an idiot.

Hey, oh, be nice to yourself. InfiniteGlass is an amazing creation!

**Comment by redhog** [comment]
Blocked by https://github.com/redhog/InfiniteGlass/issues/63

**Comment by BackOrder** [comment]
You have so much progress today according to the commits. Great!

Did you add the pointer svg? I saw that you wrote the code allowing to have a custom mouse pointer. The one in my videos are part of the Font Awesome that you have shown me before.

**Comment by redhog** [comment]
No sorry, that's not what those commits do. They just let shader code know where the pointer is, so that window decorations can be shown/hidden/made half transparent depending on that...

**Comment by BackOrder** [comment]
Thanks for explaining. No worries here, you're on a roll!

**Comment by redhog** [comment]
Moved the submenu stuff to https://github.com/redhog/InfiniteGlass/issues/64
