### ISSUE TITLE
Error reporting needs clarifications

### ISSUE THREAD

**Issue by BackOrder** [redhog/InfiniteGlass#56]
[InfiniteGlass-20200306-1606.log](https://github.com/redhog/InfiniteGlass/files/4300412/InfiniteGlass-20200306-1606.log)

**Comment by redhog** [comment]
That's actually not iceauth. That's a component failure. Try a git pull and retry and I've fixed so that it should tell you what's actually wrong.

**Comment by BackOrder** [comment]
Ooooh. The error reporting is much better but it's a little embarrassing. I had prepare for a pull request with some modifications for docker but my `~/.config/glass/ghosts.json` had customization not available in the default InfiniteGlass. Basically, it crashed because it didn't find Sakura.

Perhaps it would be a good thing to have the choice to either use host or local config.

**Comment by redhog** [comment]
Aha :) No worries. We have run into this before, and I promised you better error reporting for failed components, but never actually got around to that... But now it's fixed...
