### ISSUE TITLE
Picking bug

### ISSUE THREAD

**Issue by redhog** [redhog/InfiniteGlass#63]
The logic here

* https://github.com/redhog/InfiniteGlass/blob/master/glass-renderer/view.c#L134
* https://github.com/redhog/InfiniteGlass/blob/master/glass-theme/glass_theme/shaders/lib/fragment_picking.glsl#L13

seems broken, and sometimes mangles the window id. 0x1000007 gets transformed into 0x1000008. Why?

**Comment by redhog** [comment]
Any hints why this would not work, and fail this way, in https://en.wikipedia.org/wiki/Single-precision_floating-point_format ?

**Comment by BackOrder** [comment]
Seems like an error cause by rounding from floor().

**Comment by redhog** [comment]
But... floor shouldn't round, riiight? https://www.khronos.org/registry/OpenGL-Refpages/gl4/html/floor.xhtml

**Comment by BackOrder** [comment]
Well, output the values and manually calculate the numbers. You can also try casting instead of floor.

**Comment by redhog** [comment]
Fixed it, I think: https://github.com/redhog/InfiniteGlass/commit/3b285d6ce057fb3e3b13d9c84daa778cf4a328b8
