### ISSUE TITLE
Configuration language

### ISSUE THREAD

**Issue by redhog** [redhog/InfiniteGlass#70]
Check out JSON5, I think it's the way to go for config files: https://json5.org/

https://pypi.org/project/json5/ for Python programming.

Currently, the config files are parsed by a yaml parser. They are all JSON, but I use a yaml parser so that you can embed comments in them - I felt like example config files / templates without comments are pretty useless...

**Comment by redhog** [comment]
Re. the python package: "Known issues: Did I mention that it is SLOW?"

**Comment by BackOrder** [comment]
There is no point to move to JSON5 if it slows down InfiniteGlass. We kinda need to make it faster, not slower. :)

**Comment by redhog** [comment]
Switched to YAML for all config.
