### ISSUE TITLE
Docker will not launch InfiniteGlass, again.

### ISSUE THREAD

**Issue by BackOrder** [redhog/InfiniteGlass#71]
```
Digest: sha256:983fd33ceeae9914d50f33468cb0b03be7d0f759cf5785ba2ae5eaffea46bde2
Status: Downloaded newer image for redhogorg/glass:0.0.2
root@meep:/# 
```

**Comment by BackOrder** [comment]
```
Digest: sha256:983fd33ceeae9914d50f33468cb0b03be7d0f759cf5785ba2ae5eaffea46bde2
Status: Downloaded newer image for redhogorg/glass:0.0.2
root@centralis:/# 
```

**Comment by BackOrder** [comment]
Something is not right. No fractals, no islands. I had to do a `cd /InfiniteGlass; make run` manually.

https://github.com/redhog/InfiniteGlass/blob/master/scripts/docker-runner.sh

**Comment by BackOrder** [comment]
Caught this strange error while building the docker...

```
Processing PyGObject-3.36.0.tar.gz
Writing /tmp/easy_install-la44f01x/PyGObject-3.36.0/setup.cfg
Running PyGObject-3.36.0/setup.py -q bdist_egg --dist-dir /tmp/easy_install-la44f01x/PyGObject-3.36.0/egg-dist-tmp-za42w3n2
Package gobject-introspection-1.0 was not found in the pkg-config search path.
Perhaps you should add the directory containing `gobject-introspection-1.0.pc'
to the PKG_CONFIG_PATH environment variable
No package 'gobject-introspection-1.0' found
error: Setup script exited with Command '('pkg-config', '--print-errors', '--exists', 'gobject-introspection-1.0 >= 1.46.0')' returned non-zero exit status 1.

Try installing it with: 'sudo apt install libgirepository1.0-dev'
Makefile:41: recipe for target 'build/env/bin/glass-action' failed
make: *** [build/env/bin/glass-action] Error 1
```

**Comment by redhog** [comment]
Wow! That sounds liuke PyGObject changed and is broken in the latest version?

**Comment by BackOrder** [comment]
Exactly!

**Comment by BackOrder** [comment]
It's like a chain of events leading Cairo to fail also and finally glass-action m

**Comment by redhog** [comment]
yeah, if any of the dependencies fails install, everything comes down on your head...

**Comment by redhog** [comment]
Maybe try to hard-code an earlier version number for that library?

**Comment by BackOrder** [comment]
Can't we just move back to the previous version?

**Comment by redhog** [comment]
Yeah, but you'd probably have to hard code that - right now I haven't pinned any versions - everything just uses latest...

**Comment by BackOrder** [comment]
Would it be possible that the redhogorg/glass docker image is broken? I tried a couple Ubuntu images, one python image, several ways to install the proper Python requirements, etc. Nothing would work. Then running redhogorg/glass container will go directly to a bash prompt.

**Comment by redhog** [comment]
Things to try:

Remove the docker image and any cached non-tagged images.
Rebuild the image locally.

If this still doesn't work, check out a really old InfiniteGlass version and retry the same. If this works, work your way forward using "git bisect" to find the faulty version.
If this does not work, there are only two possibilities:
* Build fails due to changes in upstream versions
* Your docker install is somehow broken

I'll try to build this myself too ASAP and see if it works for me

**Comment by BackOrder** [comment]
Rebuild didn't work but `git checkout 14030eba7614589eab5489b6eac7ac418cc79958` et `make run-in-docker` work.

Take also note that python 2 is deprecated and caused some troubles in the newer docker container. Thus, it is necessary to remove `RUN apt install -y python` from the Dockerfile.

**Comment by redhog** [comment]
Hm, the RUN apt install -y python  is to make the alternatives work, so that writing "python" will start python3, not just "python3"...

**Comment by redhog** [comment]
Thanks  btw, that should be enough to debug this. I must have added some dependency somewhere after that that's broken.

**Comment by BackOrder** [comment]
RE: different checkouts

Commits in chronological order (from older to newer):

7a7e7637e4b9111a1efeeddccba6b1a926fbf975 working
8720ca30fa2698541a777de7128cf0a529b7ecb4 working
3b0e44b784306073deedf72e5e4117b569e6f0ca NOT WORKING (here's the problem, doc)
5d06531aed1ae478cd4b5b89673b89a8438de9b9 NOT working
dc67c27b784378c5d3ff9e174431f8a7f8395eb0 NOT working

**Comment by BackOrder** [comment]
The absolute strangest thing is that only one Python file was modified in this commit. The code itself doesn't seem to be problematic. 

https://github.com/redhog/InfiniteGlass/blob/3b0e44b784306073deedf72e5e4117b569e6f0ca/glass-input/glass_input/actions/item_pan.py#L37

Line 37 has hidden characters!

**Comment by BackOrder** [comment]
False alarm. They are just spaces. :(
