### ISSUE TITLE
Wayland support

### ISSUE THREAD

**Issue by IanTrudel** [redhog/InfiniteGlass#78]
Wayland on Wikipedia: https://en.wikipedia.org/wiki/Wayland_(display_server_protocol)

https://wayland.freedesktop.org/

https://wayland.freedesktop.org/architecture.html

![image](https://user-images.githubusercontent.com/8844578/78736467-3a744e00-791b-11ea-9dd0-d896b3da6148.png)

The Wayland Protocol: https://wayland.freedesktop.org/docs/html/

Someday, someday.

**Comment by redhog** [comment]
For now I think this is too big a rewrite to be feasible on a realistic time scale, so closing this ticket for now.
